language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        
    - os: osx
      osx_image: xcode9.2
      env:
        - MATRIX_EVAL="rm '/usr/local/include/c++' && brew install gcc && CC=gcc-7 && CXX=g++-7"

before_install:
  - test -n $CC  && unset CC
  - test -n $CXX && unset CXX
  - eval "${MATRIX_EVAL}"
  - g++ --version
  - cmake --version

script:
- cmake CMakeLists.txt
- make tests
#- make tms
#- ./tms tests/DefaultTest.txt
#- cat out_min.txt
